/**
 *
 * $Id$
 */
package ppgi.ufam.edu.robot_system.validation;

/**
 * A sample validator interface for {@link ppgi.ufam.edu.robot_system.Element}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ElementValidator {
	boolean validate();

	boolean validateId(String value);

	boolean validateFault_tolerant(boolean value);

	boolean validateEssential(boolean value);

	boolean validateDescription(String value);
}
